### ISSUE TITLE
onclick doesn't trigger class change

### ISSUE THREAD

**Issue by sebastianjung** [vanderb/vue-badger-accordion#1] opened 2018-11-05 08:58 UTC
As the title says. A Click on the header does not trigger the class to change and therefore set the max-height to 0. 

Edit: standard styles are applied. Just the js does not seems to work.

setup:
app.js
```
import { BadgerAccordion, BadgerAccordionItem } from 'vue-badger-accordion'
Vue.component('BadgerAccordion', BadgerAccordion)
Vue.component('BadgerAccordionItem', BadgerAccordionItem)
```

html
```
<badger-accordion>
    <badger-accordion-item>
        <template slot="header">test</template>
        <p slot="content">
            test
        </p>
    </badger-accordion-item>
    <badger-accordion-item>
        <template slot="header">test</template>
        <p slot="content">
            test
        </p>
    </badger-accordion-item>
</badger-accordion>
```

**Comment by mturnbu** [comment] 2018-11-09 19:47
I'm having a similar problem to the user above.

At the bottom I have

```
<script>
import {BadgerAccordion, BadgerAccordionItem} from 'vue-badger-accordion'

export default {

  name: 'projectContentVue',
  props: ['name'],
  components: {
        BadgerAccordion,
        BadgerAccordionItem
    },
  data: function(){
    return{
      contentName: name
    }
  }
}
  </script>
```

In my template section I have:
```

<badger-accordion>
    <badger-accordion-item>
        <h4 slot="header">First Accordion Header</h4>    
        <p slot="content">First Accordion Content</p>  
    </badger-accordion-item>

    <badger-accordion-item>
        <h4 slot="header">Second Accordion Header</h4>    
        <p slot="content">Second Accordion Content</p>  
    </badger-accordion-item>
</badger-accordion>
```

The html template fills in find but the js events are not happening - are you aware of any potential conflicts or reasons this might occur?

**Comment by tomhatzer** [comment] 2018-11-21 08:44
@vanderb There seems to be a general problem with the component. It doesn't trigger anything and also nothing is hidden.

That's how it looks like with the default implementation:
**Imports and global assignment:**
```
import {BadgerAccordion, BadgerAccordionItem} from 'vue-badger-accordion';

Vue.component( 'BadgerAccordion', BadgerAccordion );
Vue.component( 'BadgerAccordionItem', BadgerAccordionItem );
```

**HTML tags:**
```
<badger-accordion :options="badgerOptions">
    <badger-accordion-item>
      <template slot="header">First Accordion Header</template>
      <template slot="content">First Accordion Content</template>
    </badger-accordion-item>
    <badger-accordion-item>
      <template slot="header">First Accordion Header</template>
      <template slot="content">First Accordion Content</template>
    </badger-accordion-item>
    <badger-accordion-item>
      <template slot="header">First Accordion Header</template>
      <template slot="content">First Accordion Content</template>
    </badger-accordion-item>
    <badger-accordion-item>
      <template slot="header">First Accordion Header</template>
      <template slot="content">First Accordion Content</template>
    </badger-accordion-item>
    <badger-accordion-item>
      <template slot="header">First Accordion Header</template>
      <template slot="content">First Accordion Content</template>
    </badger-accordion-item>
</badger-accordion>
```

**Output:**
![image](https://user-images.githubusercontent.com/3952168/48829108-c232da00-ed71-11e8-8c69-8cfb6a5f1af5.png)

**EDIT:** The latest commit seems to break things. The event is not emitted, so the javascript for the Badger Accordion is never called. Reverting the code to before the commit works again.

**EDIT 2:** Found the error and created a PR to fix this issue.

**Comment by tomhatzer** [comment] 2018-11-21 09:00
@sebbler1337 @mturnbu can you please confirm that my PR fixes your issues?

**Comment by vanderb** [comment] 2018-11-26 11:20
@tomhatzer Thanks for the fix. I can confirm, this works great.

I merged your fix and updated the package. 
Please update to v 1.0.7

**Closed as completed by vanderb** 2018-11-26 11:20 UTC
